#!/bin/bash 
# 修改默认网关地址
change_default_ip() {
    local new_ip="10.0.0.1"

    # 修改网络配置中的默认 IP 地址
    uci set network.lan.ipaddr="$new_ip"
    uci commit network
}

# 设置主机名信息iStoreNAS
change_hostname() {
    local new_hostname="Xwrt"

    # 设置主机名
    uci set system.@system[0].hostname="$new_hostname"
    uci commit system

    # 同时更改 /proc/sys/kernel/hostname 文件
    echo "$new_hostname" > /proc/sys/kernel/hostname
}

# 追加编译作者信息
modify_firmware_description() {
    # 修改 /etc/openwrt_release 文件中的 DISTRIB_DESCRIPTION 字段
    sed -i "s/\(DISTRIB_DESCRIPTION='.*\)'/\1 Compiled by xding'/" /etc/openwrt_release
}

# 调用函数
change_default_ip
change_hostname
modify_firmware_description

# 移除脚本文件以确保它只运行一次
rm -f /etc/uci-defaults/99-custom