name: Dynamic Download and Build ImmortalWRT 
 
on:
  workflow_dispatch:
    inputs:
      version:
        description: '输入目标版本号（例如24.10.0）'
        required: true 
        default: '24.10.1'
      model_id:
        description: '选择机型ID'
        required: true 
        default: 'qihoo_360t7'
        type: choice 
        options:
          - qihoo_360t7 
          - redmi_ax6-stock 
      packages:
        description: '选择要编译的包（用空格分隔），可用 -pkg 排除包'
        required: false 
        default: 'luci-app-upnp luci-app-timedreboot luci-app-qosmate luci-app-taskplan luci-app-vlmcsd luci-app-passwall2 luci-app-argon-config luci-theme-argon luci-app-wizard uci -luci-i18n-base-zh-cn'
 
jobs:
  download-build:
    runs-on: ubuntu-22.04 
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
 
      - name: Install Build Dependencies 
        run: |
          sudo apt-get -qq update 
          sudo apt-get -qq install -y \
            ack antlr3 asciidoc autoconf automake autopoint \
            binutils bison build-essential bzip2 ccache cmake \
            cpio curl device-tree-compiler fastjar flex gawk \
            gettext gcc-multilib g++-multilib git gperf haveged \
            help2man intltool libc6-dev-i386 libelf-dev libfuse-dev \
            libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev \
            libmpfr-dev libncurses5-dev libncursesw5-dev \
            libpython3-dev libreadline-dev libssl-dev libtool \
            lrzsz mkisofs msmtp ninja-build p7zip p7zip-full \
            patch pkgconf python2.7 python3 python3-pyelftools \
            python3-setuptools qemu-utils rsync scons \
            squashfs-tools subversion swig texinfo uglifyjs \
            upx-ucl unzip vim wget xmlto xxd zlib1g-dev 
            
      - name: Install dependencies 
        run: bash  scripts/install-deps.sh  
 
      - name: Get Target Platform 
        id: get-target 
        run: bash  scripts/get-platform.sh  ${{ inputs.version  }} ${{ inputs.model_id  }}
 
      - name: Download and Extract ImageBuilder 
        run: bash  scripts/download-extract.sh  ${{ inputs.version  }} ${{ steps.get-target.outputs.target_platform_slash  }} ${{ steps.get-target.outputs.target_platform_hyphen  }}

      - name: Configure Repositories 
        run: bash scripts/config-repos.sh 
 
      # - name: Process Package List 
      #   id: process-packages 
      #   run: bash  scripts/process-packages.sh  "${{ inputs.packages  }}" 
 
      - name: Build Firmware 
        run: 
          # bash  scripts/secure-setup.sh
          bash  scripts/build-firmware.sh  ${{ inputs.model_id  }} "${{ inputs.packages  }}" 
 
      - name: Upload Artifacts 
        uses: actions/upload-artifact@v4 
        with:
          name: firmware-${{ inputs.model_id  }}-${{ inputs.version  }}
          path: immortalwrt-imagebuilder-*/bin/targets/${{ steps.get-target.outputs.target_platform_slash  }}